replicaCount: 1

image:
  repository: keycloak
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8080

ingress:
  enabled: true
  host: ""
  tls: false

env: {}
secretEnv: {}

resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

healthCheck:
  path: /health
  initialDelaySeconds: 60
  periodSeconds: 10
